#!/usr/bin/env python 
EVENTS = [  'Afterglow',
	   		'Breakfast',
			'Breakouts_Rotation_I',
			'Breakouts_Rotation_II',
			'Closing_General_Session',
			'Continue_General_Session_Set-Up',
	   		'CRN_Breakfast',
			'CRN_Lunch',
	   		'CRN_Meeting',
			'CRN_Reception',
			'Departures_for_those_not_attending_post_trips',
			'Departures_for_post_trips',
			'Evening_Event_Departures',
			'First_Timers_Orientation',
			'First_Timers_Reception',
			'General_Session_Set-Up',
			'Grab&Go_or_Stay&Play_Lunch'
			'Hospitality_Registration',
	   		'Hospitality_Registration_STS_Set-Up',
			'Marketplace_Set-Up',
			'Marriott_Marketplace',
			'Opening_General_Session',
			'Opening_Reception/Party',
			'Party_sponsored_by_LACVB',
			'Peer_to_Peer_Breakfast',
			'Pool_Party_to_Free_Time',
			'Spirit_to_Serve',
			'Set_Rest_of_Marketplace',
			'Tours_of_JW_Marriott_and_Ritz-Carlton',
		]
LOCATIONS = ['Diamond1','Diamond2','Diamond3','Diamond4','Diamond5','Diamond6','Diamond7','Diamond8','Diamond9','Diamond10',
		  	'Diamond_Ballroom',
			'Fords_Filling_Station',
		  	'Georgia_Room',
			'Gold1','Gold2','Gold3',
			'Gold_Ballroom',
			'JW_Front_Drive',
			'Mixing_Room',
			'PlatinumA','PlatinumB','PlatinumC','PlatinumD','PlatinumE','PlatinumF','PlatinumG','PlatinumH','PlatinumI','PlatinumJ',
			'The_Edison',
			'The_Novo_by_Microsoft',
			'Vibiana',
			'West_Road',
			'WP24',
			]	

SESSIONS = [

			]
